document.addEventListener('DOMContentLoaded',function(){
var fix=document.createElement('style');
fix.textContent='.human-holo,.holo-person,.holo-camera,.holo-chat-line{display:none!important}.holo-social{width:170px!important;height:135px!important;opacity:.65!important;filter:drop-shadow(0 0 18px rgba(56,213,255,.45))!important}.holo-social:before{content:"";position:absolute;left:50%;top:20px;width:82px;height:82px;transform:translateX(-50%);border-radius:50%;border:1px solid rgba(56,213,255,.55);background:radial-gradient(circle,rgba(56,213,255,.25),rgba(69,255,147,.08),transparent 70%);box-shadow:0 0 30px rgba(56,213,255,.35),inset 0 0 20px rgba(56,213,255,.16)}.holo-social:after{content:"AI SIGNAL";position:absolute;left:50%;top:52px;transform:translateX(-50%);font-family:Orbitron,sans-serif;font-size:.62rem;letter-spacing:1.5px;color:rgba(224,252,255,.8);text-shadow:0 0 14px rgba(56,213,255,.75)}.holo-caption{bottom:3px!important;min-width:135px!important;font-size:.58rem!important}.holo-agent{opacity:.55!important}.holo-body{border-radius:28px!important}.holo-arm{display:none!important}';
document.head.appendChild(fix);
var chat=document.getElementById('chatbot'),msgs=document.getElementById('chatMessages'),inp=document.getElementById('chatInput'),send=document.getElementById('sendBtn');
var toggle=document.getElementById('chatToggle'),openBtn=document.getElementById('openChat'),closeBtn=document.getElementById('closeChat');
var history=[];
function open(){if(chat)chat.style.display='flex'}
function close(){if(chat)chat.style.display='none'}
function add(t,c){if(!msgs)return null;var d=document.createElement('div');d.className=c;d.innerText=t;msgs.appendChild(d);msgs.scrollTop=msgs.scrollHeight;return d}
function ctx(){return{details:document.getElementById('details')?.value||'',budget:document.getElementById('budget')?.value||'',timeline:document.getElementById('timeline')?.value||'',selected:[...document.querySelectorAll('.package-card.selected')].map(x=>x.dataset.service)}}
function backup(t){t=String(t||'').toLowerCase();if(t.includes('price')||t.includes('cost'))return 'I can help price it smart. Small edits and AI videos can start low, starter websites are usually $75–$175+, and bigger website/automation bundles can be $100–$600+ depending on scope. The $5 deposit starts review only.';if(t.includes('website'))return 'For a website, I would start with a clean one-page build: hero, services, portfolio, testimonials, contact/book button, and SEO basics. Add chatbot, payments, or custom orders if you want it more advanced.';if(t.includes('automation'))return 'Automation works best when it saves repeated work: leads, follow-ups, reminders, forms, order details, and content workflows. Tell me what task you repeat the most.';return 'I can help with websites, automations, AI videos, content, branding, pricing, and custom digital builds. Tell me your business, goal, deadline, and budget vibe.'}
async function ask(t){try{var r=await fetch('/chat-ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:t,orderContext:ctx(),history:history.slice(-8)})});if(!r.ok)throw 0;var j=await r.json();return j.reply||backup(t)}catch(e){return backup(t)}}
async function go(raw){var v=(raw||inp?.value||'').trim();if(!v)return;open();add(v,'user-message');history.push({role:'user',content:v});if(inp)inp.value='';var wait=add('Thinking...','bot-message');var reply=await ask(v);if(wait)wait.innerText=reply;history.push({role:'assistant',content:reply})}
if(toggle)toggle.onclick=open;if(openBtn)openBtn.onclick=open;if(closeBtn)closeBtn.onclick=close;if(send)send.onclick=function(e){e.preventDefault();go()};if(inp)inp.addEventListener('keydown',function(e){if(e.key==='Enter'){e.preventDefault();go()}});
document.querySelectorAll('.chat-quick-buttons button').forEach(function(b){b.onclick=function(e){e.preventDefault();go(b.innerText)}});
});
