document.addEventListener('DOMContentLoaded',function(){var pay=document.querySelector('.stripe-button');if(pay){pay.style.display='none'}var submit=document.querySelector('#orderForm button[type="submit"]');if(submit){submit.style.display='none'}var q=new URLSearchParams(location.search);if(q.get('checkout')==='success'){var box=document.getElementById('formSuccess');if(box){box.style.display='block';box.textContent='Your order has been sent and your review spot is secured.'}}
var buddy=['Your systems are evolving.','Someone is checking memberships.','Creative team incoming.','Need another AI build?','Premium package recommended.','AI command center synced.','Your automation is online.','This website is alive.'];
var human=['Two creators are reviewing a campaign.','A creator is recording promo content.','AI analysts are checking dashboard activity.','A strategist is reviewing automation charts.','Ambient hologram staff moving through workspace.'];
function pick(a){return a[Math.floor(Math.random()*a.length)]}
function stage(){var s=document.querySelector('.holo-stage');if(!s){s=document.createElement('div');s.className='holo-stage';document.body.appendChild(s)}return s}
function makePerson(c){return '<div class="human-holo '+c+'"><div class="head"></div><div class="torso"></div><div class="arm left"></div><div class="arm right"></div><div class="leg left"></div><div class="leg right"></div></div>'}
function people(){var s=stage();var w=document.createElement('div');var talk=Math.random()>.35;w.className='holo-social active '+(talk?'talk':'photo');var side=Math.random()>.5?'left':'right';w.style[side]='-270px';w.style.top=(18+Math.random()*48)+'vh';w.innerHTML=talk?makePerson('one')+makePerson('two')+'<div class="holo-chat-line"></div><div class="holo-caption">'+pick(human)+'</div>':makePerson('solo')+'<div class="holo-camera"></div><div class="holo-caption">'+pick(human)+'</div>';s.appendChild(w);setTimeout(function(){w.style.transition='all 9s linear';w.style.transform='translateX('+(side==='left'?'60vw':'-60vw')+')'},60);setTimeout(function(){var c=w.querySelector('.holo-caption');if(c)c.textContent='The holograms noticed you.'},5200);setTimeout(function(){w.classList.add('glitch-out');setTimeout(function(){w.remove()},850)},9000)}
function buddyTalk(){document.querySelectorAll('.holo-bubble').forEach(function(b){if(Math.random()>.35){b.innerHTML='<strong>AI Buddy</strong>'+pick(buddy)}})}
setTimeout(people,2500);setInterval(people,16000);setInterval(buddyTalk,7000);
});